# Generated by Django 4.1 on 2023-07-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_transaction_delete_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='amount',
        ),
    ]
